# -*- coding: utf-8 -*-
"""Levenshtein_distance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yLJtHcQbRNxwZAPw-5LA6MAAu_Nqf-ph
"""

source = 'heyo'
target = 'hello'
def edit_distance(source, target):
  distances = []
  for i in range(len(source)+1):
    distances.append([0] * (len(target) + 1))
  for i in range(len(source)+1):
    distances[i][0] = i
  for i in range(len(target)+1):
    distances[0][i] = i
  print(distances)

  del_cost = 0
  ins_cost = 0
  sub_cost = 0

  for i in  range(1,len(source)+1):
    for j in range(1, len(target)+1):
      if source[i-1] == target[j-1]:
        distances[i][j] = distances[i-1][j-1]
      else:
        del_cost = distances[i-1][j] + 1
        ins_cost = distances[i][j-1] + 1
        sub_cost = distances[i-1][j-1] + 1

        distances[i][j] = min(del_cost, ins_cost, sub_cost)
  results = distances[-1][-1]
  return results


edit_distance(source, target)